---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#packages
library(stringr)
library(knitr)
```



```{r load}
#Load the raw data
raw_data<-read.csv("week 3/raw data/Week 3 Example Data.csv")

#Create a copy of the raw data
data<-raw_data
```


```{r restructure}

#rename TIPI columns
colnames(data)[6:15]<-paste0("tipi",
                             rep(c("E","A","C","N","O"),2),
                             1:10)

#Append an R to reverse code
colnames(data)[c(7,11,13:15)]<-paste0(colnames(data)[c(7,11,13:15)],"R")

###Restructure Variables###

#split the condition variable into two columns
conditionSplit<-str_split_fixed(data$condition,"_",2)

#rename the newly created condition variables
colnames(conditionSplit)<-c("shockCause","pMoral")

#Add the split columns to the data
data<-cbind(data,conditionSplit)

data<-data[,-4]

#recodes missing value as NAsa
data$guilt<-ifelse(data$guilt==-99,NA,data$guilt)
```



```{r compute}

#for reverse coding add -1*data so the number is opposite +highest number on scale plus 1 at the end (8). Reverse code for the relevant TIPI items

data[,c(6,10,12:14)]<-(-1*data[,c(6,10,12:14)])+8

#compute composite personality scores
data$extra<-rowMeans(data[,c(5,10)])
data$agree<-rowMeans(data[,c(6,11)])
data$consc<-rowMeans(data[,c(7,12)])
data$neuro<-rowMeans(data[,c(8,13)])
data$open<-rowMeans(data[,c(9,14)])


```



```{r codebook}
#Rearrange 
data<-data[,c(1:3,5:14,20:24,4,18:19,15:17)]

codebook<-data.frame("variable"=colnames(data))

codebook$description<-c(
  "Participant ID Number",
  "Participant Sex",
  "Age",
  "TIPI Extraversion 1",
  "TIPI Agreeableness 1(R)",
  "TIPI Conscientiousness 1",
  "TIPI Neuroticism 1",
  "TIPI Openness 1",
    "TIPI Extraversion 2(R)",
  "TIPI Agreeableness 2",
  "TIPI Conscientiousness 2(R)",
  "TIPI Neuroticism 2(R)",
  "TIPI Openness 2(R)",
  "Composite Extraversion",
  "Composite Openness",
  "Composite Agreeableness",
  "Composite Conscientiousness",
  "Composite Neuroticism",
  "Shock Voltage",
  "Shock Cause (Participant vs. Partner",
  "Partner Morality (good vs. bad)",
  "Amount of Money shared with Partner (pre-shock)",
  "Amount of Money shared with Partner (post-shock)",
  "Guilt Reported by Partcipant"
)
#saves the data type for each variable
codebook$type<-sapply(data,class)

#output the codebook as a table
kable(codebook)

```


```{r save}

write.csv(data,"week 3/processed data/Week 3 DATA PROCESSED.csv")

```

